# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Arraymaker
                                 A QGIS plugin
 Makes points in a circle around a central point
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-27
        copyright            : (C) 2020 by Morten Sickel / NORSAR
        email                : morten@norsar.no
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Arraymaker class from file Arraymaker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Arraymaker import Arraymaker
    return Arraymaker(iface)
