# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Arraymaker
                                 A QGIS plugin
 Makes points in a circle around a central point
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-01-27
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Morten Sickel / NORSAR
        email                : morten@norsar.no
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
https://gis-ops.com/qgis-3-use-interactive-mapping/

"""
from PyQt5.QtCore import pyqtSignal, QVariant
from PyQt5.QtGui import QCursor, QPixmap
from PyQt5.QtWidgets import QApplication

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject, QgsPoint,QgsPointXY, QgsFeature, Qgis, QgsVectorLayer, QgsField, QgsGeometry, QgsMapLayerProxyModel

import math
from qgis.gui import QgsMapToolEmitPoint, QgsVertexMarker, QgsMessageBar

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .Arraymaker_dialog import ArraymakerDialog
import os.path

class PointTool(QgsMapToolEmitPoint):

    def __init__(self, canvas):

        QgsMapToolEmitPoint.__init__(self, canvas)
        self.canvas = canvas
        self.centre = True

    canvasClicked = pyqtSignal('float')
    def canvasReleaseEvent(self, event):
        # Get the click and emit a transformed point
        self.createarray(event.mapPoint())
        
        
    def makepoint(self,x,y,name):
        pnt=QgsPoint(x,y)
        f = QgsFeature()
        f.setGeometry(pnt)
        if self.rlayer==None:
            height=-9999
            res=False
        else:
            height, res = self.rlayer.dataProvider().sample(QgsPointXY(x,y),1)
        if math.isnan(height):
            height=-9999
            self.iface.messageBar().pushMessage("Arraybuilder - Warning", "Could not read value from raster layer", level=Qgis.Warning)
        
        self.lowest=min(height,self.lowest)
        self.highest=max(height,self.highest)
        f.setAttributes([None,height,self.version,name])
        f=self.pvd.addFeatures([f])
        self.pvd.forceReload()
        repstring="{} {} {} {}".format(name,round(x), round(y),round(height,1))
        self.dlg.TEReport.append(repstring)
        return(f[1][0].id())


    def createarray(self,pointTool):
        try:
            x=pointTool.x()
            y=pointTool.y()
            # First click gives centre point
            if self.centre: 
                self.dlg.TEReport.append("Version : {}".format(self.version))
                self.lowest=10000
                self.highest=-10000
                #self.version+=1
                self.dlg.SBVersion.setValue(self.version+1)
                if len(self.namebase)>1:
                    name=self.namebase[:-1]+'A0'
                else:
                    name=self.namebase+'A0'
                if self.workinglayer.selectedFeatureCount()==1:
                    x=self.workinglayer.selectedFeatures()[0].geometry().asPoint()[0]
                    y=self.workinglayer.selectedFeatures()[0].geometry().asPoint()[1]
                else:
                    self.ids.append(self.makepoint(x,y,name))
                self.cx=x
                self.cy=y
                self.centre=False
                self.iface.messageBar().pushMessage("Arraybuilder", "Click in the direction of the first circle element", level=Qgis.Info,duration=3)
            else:
                dx=x-self.cx
                dy=y-self.cy
                if dy!=0:
                    rads=math.atan(dx/dy)
                else:
                    rads=0
                direction="Direction first point, {} degrees".format(round(math.degrees(rads),1))
                distance=math.sqrt(dx**2+dy**2)
                # Next time, will select centre element
                self.centre=True
                factor=self.radius/distance
                relx=factor*dx
                rely=factor*dy
                x=self.cx+relx
                y=self.cy+rely
                name=self.namebase+'0'
                self.ids.append(self.makepoint(x,y,name))
                ddeg=self.ddeg
                for i in range(1,self.npoints):
                    tx=math.cos(ddeg)*relx-math.sin(ddeg)*rely
                    ty=math.sin(ddeg)*relx+math.cos(ddeg)*rely
                    relx=tx
                    rely=ty
                    name=self.namebase+'{}'.format(i)
                    self.ids.append(self.makepoint(self.cx+relx,self.cy+rely,name))
                print(self.ids)
                self.workinglayer.removeSelection()
                self.workinglayer.select(self.ids)
                self.dlg.TEReport.append("Highest : {}".format(round(self.highest,1)))
                self.dlg.TEReport.append("Lowest  : {}".format(round(self.lowest,1)))
                self.dlg.TEReport.append("Range   : {}".format(round(self.highest-self.lowest,1)))
                self.dlg.TEReport.append(direction)
                self.canvasClicked.emit(round(self.highest-self.lowest,1))    
        except AttributeError as e:
            print(e)
            print("Nothing so far")
            pass
        except ZeroDivisionError:
            self.iface.messageBar().pushMessage("Arraybuilder", "Division by zero. Start over", level=Qgis.Critical,duration=5)
            self.centre=True

class Arraymaker:
    """QGIS Plugin Implementation."""
    # TODO: Set up to type in centre coordinates and direction
    
    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Arraymaker_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Arraymaker')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Arraymaker', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=False,
        status_tip="To create a regular circle pattern e.g. for an array",
        whats_this="To create a regular circle pattern e.g. for an array",
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Arraymaker/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Arraybuilder'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Arraymaker'),
                action)
            self.iface.removeToolBarIcon(action)
    
    



    def run(self):
        """Run method that performs all the real work"""
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ArraymakerDialog(parent=self.iface.mainWindow())
            self.dlg.MLWork.setFilters(QgsMapLayerProxyModel.PointLayer)
            self.dlg.MLValue.setFilters(QgsMapLayerProxyModel.RasterLayer)
            self.dlg.PBDefine.clicked.connect(self.startarray)
            self.dlg.PBNewLayer.clicked.connect(self.createlayer)
            self.dlg.finished.connect(self.result)

        # show the dialog
        self.last_maptool = self.iface.mapCanvas().mapTool()
        self.dlg.open()
     
    def createlayer(self):
                
        # create layer
        vl = QgsVectorLayer("Point", "temporary_array", "memory")
        pr = vl.dataProvider()
        # Set projection for layer as the project projection
        crs=QgsProject.instance().crs()
        vl.setCrs(crs)
        # add fields
        pr.addAttributes([
            QgsField("id",  QVariant.Int),
            QgsField("height",  QVariant.Double),
            QgsField("version", QVariant.Int),
            QgsField("name",    QVariant.String)
            ])
        vl.updateFields() # tell the vector layer to fetch changes from the provider
        QgsProject.instance().addMapLayer(vl)
        self.dlg.MLWork.setLayer(vl)
     
    def startarray(self):
        self.dlg.hide()
        self.point_tool = PointTool(self.iface.mapCanvas())
        self.point_tool.rlayer = self.dlg.MLValue.currentLayer()
        self.workinglayer=self.dlg.MLWork.currentLayer()
        if self.workinglayer==None:
             self.iface.messageBar().pushMessage("Arraybuilder", "Select a (New) work layer", level=Qgis.Critical,duration=5)
             return(False)
        self.point_tool.workinglayer=self.workinglayer
        self.layername=self.workinglayer.name()
        if self.point_tool.rlayer == None:
            self.rastername=None
        else:
            self.rastername=self.point_tool.rlayer.name()
        # Todo - clean up initialization
        self.point_tool.namebase=self.dlg.LENameBase.text()
        self.point_tool.radius=self.dlg.SBRadius.value()
        self.point_tool.npoints=self.dlg.SBNpoints.value()
        self.point_tool.ddeg=math.pi*2/self.point_tool.npoints
        self.point_tool.dlg = self.dlg
        self.point_tool.iface=self.iface
        self.point_tool.version=self.dlg.SBVersion.value()
        self.point_tool.centre=True # Starting up
        self.point_tool.pvd=self.workinglayer.dataProvider()
        self.point_tool.ids=[]
        self.dlg.TEReport.clear()
        self.dlg.TEReport.append("Storing to  {}".format(self.layername))
        if self.rastername==None:
            self.dlg.TEReport.append("Not reading values")
        else:
            self.dlg.TEReport.append("Reading values from {}".format(self.rastername))
        self.iface.mapCanvas().setMapTool(self.point_tool)
        message="Click to locate the center"
        if self.workinglayer.selectedFeatureCount()==1:
            message="Click in map to define array from selected point"
        elif self.workinglayer.selectedFeatureCount()>1:
            message="Select one point to use as senter. "+message
        self.iface.messageBar().pushMessage("Arraybuilder",message , level=Qgis.Info, duration=5)
        self.point_tool.canvasClicked.connect(self.finishdefine)
    
    
    def finishdefine(self,range):
        self.point_tool.canvasClicked.disconnect()
        self.workinglayer.updateExtents()
        self.iface.mapCanvas().setMapTool(self.last_maptool)
        self.dlg.show()
        self.point_tool.centre=True
    
    def result(self,result):
        # Do I need to do this? 
        # See if OK was pressed
        if result:
           pass
                
